all:
  hosts:
    alumni:
  vars:
    vault_path_inventory: bmstu-alumni/data/main,inventory-secrets.yaml
    swarm_manager_host: alumni
    home: "/home/{{ ansible_user }}"
    letsencrypt_path: "/etc/letsencrypt"

managers:
  hosts:
    alumni:

obtain_certs:
  hosts:
    alumni: