'yes': Да
'no':  Нет

there_was_en_error: Произошла ошибка!

logout: Выйти

done:  Выполнено
super: Супер

is_active:    Регистрация активна
is_inactive:  Регистрация не активна
set_inactive: Отменить регистрацию
set_active:   Вернуть регистрацию

has_been_set_inactive: Регистрация деактивирована
has_been_set_active:   Регистрация активирована

data_empty: Не заполнено
register:   Управление регистрацией

switch:        Рубильник
groups:        Группы
users:         Пользователи
registration:  Параметры регистрации
report:        Отчет
notifications: Оповещения
keyboard:      Клавиатура
settings:      Настройки
logs:          Логи

timestamp: Метка времени
message:   Сообщение

key:         Ключ
description: Описание
value:       Значение

bot_status: Статус бота

on_male:         Включён
off_male:        Выключён
restart_planned: Назначен перезапуск
restarting:      Перезапускается
service_mode:    Сервисный режим

turn_on:         Включить
turn_off:        Выключить
restart_normal:  Перезапустить в нормальный режим
restart_service: Перезапустить в сервисный режим

is_registration_open: Статус регистрации

registration_opened: Открыта
registration_closed: Закрыта

registration_close: Закрыть регистрацию
registration_open:  Открыть регистрацию

username: Имя пользователя Телеграм

chat_id:     Id чата
status:      Статус
description: Описание

group_inactive:    Не активна
group_normal:      Обычная
group_admin:       Админы
group_super_admin: Супер админы

keyboard_keys: Клавиатура

text_markdown: Тест разметки markdwon
photo_link:    Ссылка на изображение

keyboard_key_inactive: Не активна
keyboard_key_normal:   Обычная
keyboard_key_deferred: Отложенные вопросы
keyboard_key_me:       Обо мне

field_branches: Ветки полей
fields: Поля пользователей

branch_none: Пусто

is_ui_edditable:  Можно менять в UI
is_bot_edditable: Можно менять в боте
is_deferrable:    Можно отложить
next_branch_id:    Следующая ветка

field_branch_inactive: Не активна
field_branch_normal:   Активна

order_place:       Порядок
branch_id:         Ветка
question_markdown: Вопрос Markdown
answer_options:    Варианты ответа
image_bucket:      Бакет изображений
document_bucket:   Бакет документа

field_inactive: Не активен
field_normal:   Активен

image: Изображение
document: Документ
