---
#############################################################################
# 0) Взять секреты из vault и добавить SSH ключи в known_hosts              #
#############################################################################

- name: Pull secrets from vault
  hosts: all
  gather_facts: false
  tags:
    - always
  roles:
    - role: bmstu.vats.init
      vault_path_secrets: bmstu-alumni/data/main,secrets.yaml

#############################################################################
# 1) Доступ к сертификатам                                                  #
#############################################################################

- name: Copy nginx configs and htmls
  hosts: managers
  tasks:
    - name: Add read permission on certs dir
      become: yes
      file:
        name: "{{ letsencrypt_path }}"
        mode: "u=rwX,g=rwX,o=rX"
        recurse: yes

#############################################################################
# 2) Запуск сервиса                                                         #
#############################################################################

- name: Run services
  hosts: managers
  roles:
    - role: bmstu.vats.generic_deploy
      compose_template_path: ../docker-compose.j2.yaml

      fileglobs:
        - "../nginx/*.conf"
        - "../modsecurity/*.conf"
        - "../scripts/*.sh"
      
      placement:
        nginx:             alumni
        keycloak:          alumni
        keycloak_postgres: alumni
        bot:               alumni
        backup:            alumni

      stack_name:  "bmstu-alumni-bot"
      stack_prune: true
      workdir:     "{{ home }}/bmstu-alumni-bot"
